<?php
/**
 * @file
 * Functions to support theming.
 */

function arby_theme_suggestions_block_alter(&$suggestions, $variables) {
  foreach ($suggestions as &$suggestion) {
    $suggestion = str_replace('arby_', 'classy_', $suggestion);
  }
}
function arby_theme_suggestions_taxonomy_term_alter(&$suggestions, $vars, $hook) {
  if($vars['elements']['#view_mode'] == 'card') {
    $suggestions[] = 'taxonomy_term__card'; // note underscores
  }
}
