favicon:
  mimetype: image/png
  path: 'public://logo_0_0.png'
  url: 'http://ryanbateman.space/sites/default/files/logo_0_0.png'
  use_default: 0
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://logo_0.png'
  url: ''
  use_default: 0
schemas:
  bootstrap: 8000
  reticent: 8000
